/*
 * Company: Blackaddr Audio
 * Effect Name: Noise Gate
 * Description: A noise gate wtih controllable threshold, opening and closing times and DC removal filter. Basic tuner included. 
 *
 * This file was auto-generated by Aviate Audio Effect Creator for the Multiverse.
 */
#include <cmath>
#include "Aviate/LibBasicFunctions.h"
#include "NoiseGate.h"

using namespace Aviate;

namespace BlackaddrAudio_NoiseGate {

void NoiseGate::mapMidiControl(int parameter, int midiCC, int midiChannel)
{
    if (parameter >= NUM_CONTROLS) {
        return ; // Invalid midi parameter
    }
    m_midiConfig[parameter][MIDI_CHANNEL] = midiChannel;
    m_midiConfig[parameter][MIDI_CONTROL] = midiCC;
}

void NoiseGate::setParam(int paramIndex, float paramValue)
{
    switch(paramIndex) {
    case 0 : bypass( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 1 : volume( (paramValue - 0.000000) / (10.000000 - 0.000000) ); break;
    case 2 : threshold( (paramValue - -60.000000) / (0.000000 - -60.000000) ); break;
    case 3 : attackms( (paramValue - 0.000000) / (50.000000 - 0.000000) ); break;
    case 4 : holdms( (paramValue - 0.000000) / (500.000000 - 0.000000) ); break;
    case 5 : releasems( (paramValue - 0.000000) / (500.000000 - 0.000000) ); break;
    case 6 : gate( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 7 : inputlevel( (paramValue - -70.000000) / (3.000000 - -70.000000) ); break;
    case 8 : dcfilter( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    case 9 : dcfilterenable( (paramValue - 0.000000) / (1.000000 - 0.000000) ); break;
    default : break;
    }
}

float NoiseGate::getUserParamValue(int paramIndex, float normalizedParamValue)
{
    switch(paramIndex) {
    case 0 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // bypass
    case 1 : return ( ((10.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // volume
    case 2 : return ( ((0.000000 - -60.000000) * normalizedParamValue) + -60.000000 ); // threshold
    case 3 : return ( ((50.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // attackms
    case 4 : return ( ((500.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // holdms
    case 5 : return ( ((500.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // releasems
    case 6 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // gate
    case 7 : return ( ((3.000000 - -70.000000) * normalizedParamValue) + -70.000000 ); // inputlevel
    case 8 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // dcfilter
    case 9 : return ( ((1.000000 - 0.000000) * normalizedParamValue) + 0.000000 ); // dcfilterenable
    default : return 0.0f;
    }
}

void NoiseGate::processMidi(int channel, int control, int value)
{
    float val = (float)value / 127.0f;

    if ((m_midiConfig[Bypass_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Bypass_e][MIDI_CONTROL] == control)) {
        bypass(val);
        return;
    }

    if ((m_midiConfig[Volume_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Volume_e][MIDI_CONTROL] == control)) {
        volume(val);
        return;
    }

    if ((m_midiConfig[Threshold_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Threshold_e][MIDI_CONTROL] == control)) {
        threshold(val);
        return;
    }

    if ((m_midiConfig[Attackms_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Attackms_e][MIDI_CONTROL] == control)) {
        attackms(val);
        return;
    }

    if ((m_midiConfig[Holdms_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Holdms_e][MIDI_CONTROL] == control)) {
        holdms(val);
        return;
    }

    if ((m_midiConfig[Releasems_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Releasems_e][MIDI_CONTROL] == control)) {
        releasems(val);
        return;
    }

    if ((m_midiConfig[Gate_e][MIDI_CHANNEL] == channel) && (m_midiConfig[Gate_e][MIDI_CONTROL] == control)) {
        gate(val);
        return;
    }

    if ((m_midiConfig[InputLevel_e][MIDI_CHANNEL] == channel) && (m_midiConfig[InputLevel_e][MIDI_CONTROL] == control)) {
        inputlevel(val);
        return;
    }

    if ((m_midiConfig[DCFilter_e][MIDI_CHANNEL] == channel) && (m_midiConfig[DCFilter_e][MIDI_CONTROL] == control)) {
        dcfilter(val);
        return;
    }

    if ((m_midiConfig[DCFilterEnable_e][MIDI_CHANNEL] == channel) && (m_midiConfig[DCFilterEnable_e][MIDI_CONTROL] == control)) {
        dcfilterenable(val);
        return;
    }

}

audio_block_t* NoiseGate::m_basicInputCheck(audio_block_t* inputAudioBlock, unsigned outputChannel)
{
    // Check if effect is disabled
    if (m_enable == false) {
        // do not transmit or process any audio, return as quickly as possible after releasing the inputs
        if (inputAudioBlock) { release(inputAudioBlock); }
        return nullptr; // disabled, no further EFX processing in update()
    }  // end of enable check

    // check if effect is in bypass
    if (m_bypass == true) {
        // drive input directly to the specified output. ie. bypass
        if (inputAudioBlock != nullptr) {
            // valid input, drive to outputChannel if specified
            if (outputChannel >= 0) {
                transmit(inputAudioBlock, outputChannel); // drive to specified output
            }
            release(inputAudioBlock); // release the input block as we are done with it
        } else { // invalid input block, allocate a block and drive silence if specified
            if (outputChannel >= 0) {
                audio_block_t* silenceBlock = allocate();
                if (silenceBlock) {
                    clearAudioBlock(silenceBlock);  // create silence in the buffer
                    transmit(silenceBlock, outputChannel);
                    release(silenceBlock);
                }
            }
        }
        return nullptr;  // bypassed, no further EFX processing in update()
    }  // end of bypass check

    // If not disabled or bypassed, create silence if the input block is invalid then
    // return the valid audio block so update() can continue.
    if (inputAudioBlock == nullptr) {
        inputAudioBlock = allocate();
        if (inputAudioBlock == nullptr) { return nullptr; } // check if allocate was unsuccessful
        // else
        clearAudioBlock(inputAudioBlock);
    }
    return inputAudioBlock; // inputAudioBLock is valid and ready for update() processing
}

const uint8_t rblk[256] = TEENSY_AUDIO_BLOCK;
const uint8_t* NoiseGate::getRblk() { return rblk; }
static constexpr char PROGMEM NoiseGate_name[] = {0x42, 0x6c, 0x61, 0x63, 0x6b, 0x61, 0x64, 0x64, 0x72, 0x20, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x3a, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x20, 0x47, 0x61, 0x74, 0x65, 0x0};
const char* NoiseGate::getName() { return NoiseGate_name; }

}
